### Initialize
- name: Include additional on_finalize tasks
  include: "{{ on_cosnics_finalize }}"
  when: on_cosnics_finalize is defined
- name: Clear and WarmUp Chamilo cache
  shell: php {{ chamilo_directory }}/src/console chamilo:cache:clear -w
- name: ensure group has write right in cache folder
  file: path={{ project_shared_path }}/cache state=directory mode="g+w" recurse=yes
  run_once: true
- name: ensure group has write right in storage folder
  file: path={{ project_shared_path }}/storage state=directory mode="g+w"
  run_once: true
- name: ensure log folder exists and web group has write rights
  file: path={{ project_shared_path }}/storage/logs state=directory mode="g+w"
  run_once: true
- name: Remove Chat logs
  file: "path='{{ project_shared_path }}/storage/logs/phpfreechat/cache' state=absent"
  run_once: true
- name: Reset the opcache
  uri:
    url: "{{ cosnics_deploy_opcache_url }}"
    return_content: yes
  register: cosnics_deploy_opcache_result
  when: cosnics_deploy_opcache_reset
- debug: msg="{{ cosnics_deploy_opcache_result.content }}"
  when: cosnics_deploy_opcache_reset