### Initialize
- name: Include additional on_finalize tasks
  include: "{{ on_cosnics_finalize }}"
  when: on_cosnics_finalize is defined
- name: ensure group has write right in cache folder
  file: path={{ cosnics_cache_path }} state={{cosnics_cache_path_state}} mode="g+w"
  run_once: true
- name: ensure group has write right in storage folder
  file: path={{ cosnics_storage_path }} state={{cosnics_storage_path_state}} mode="g+w"
  run_once: true
- name: ensure log folder exists and web group has write rights
  file: path={{ cosnics_logs_path }} state={{cosnics_logs_path_state}} mode="g+w" recurse=yes
  run_once: true
- name: Clear and Warmup Cosnics cache
  shell: php {{ deploy_helper.new_release_path }}/console chamilo:cache:clear -w
- name: ensure group has write right in the cache sub folder of this release
  file: path={{ cosnics_cache_path }}/{{cosnics_deploy_timestamp.stdout}} state=directory mode="g+w" recurse=yes
  run_once: true #the cache folder should be shared between servers.
- name: Remove Chat logs
  file: "path='{{ cosnics_logs_path }}/phpfreechat/cache' state=absent"
  run_once: true