### Initialize
- name: Include additional on_make_shared_resources tasks
  include: "{{ on_cosnics_make_shared_resources }}"
  when: on_cosnics_make_shared_resources is defined
- name: ensure legacy webservice dir exists in web dir
  file: path={{ deploy_helper.new_release_path }}/web/application/weblcms/tool/ephorus/php/webservice state=directory mode="g+r" recurse=yes
- name: soft link the wsdl
  file: src={{ deploy_helper.new_release_path }}/src/Chamilo/Application/Weblcms/Tool/Implementation/Ephorus/Webservice/ephorus_reporting_service.wsdl dest={{ deploy_helper.new_release_path }}/web/application/weblcms/tool/ephorus/php/webservice/ephorus_reporting_service.wsdl state=link
- name: soft link the soap server
  file: src={{ deploy_helper.new_release_path }}/src/Chamilo/Application/Weblcms/Tool/Implementation/Ephorus/Webservice/ephorus_reporting_service.php dest={{ deploy_helper.new_release_path }}/web/application/weblcms/tool/ephorus/php/webservice/ephorus_reporting_service.php state=link